server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 512
  undertow:
    max-http-post-size: 100MB

spring:
  application:
    name: queqiao-server

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %highlight(%-5level) --- [%15.15t] %cyan(%-40.40logger{39}):%-4L - %X{tid} - %msg%n"